### ISSUE TITLE
Update Requirements

### ISSUE THREAD

**Issue by gabrielpie6** [RafaelCasamaximo/contExt#18]
Need to update packages requirements in "requirements.txt" and include pydicom

**Comment by RafaelCasamaximo** [comment]
Acho bom arrumar

**Comment by gabrielpie6** [comment]
### Can't download even more dependencies!

Got a new update when trying to run requirement install (pip install -r requirements.txt):

> ERROR: Could not find a version that satisfies the requirement dearpygui==1.8.0 (from versions: 1.10.1)
> ERROR: No matching distribution found for dearpygui==1.8.0

Now, when downloading dearpyguy from dearpygui==1.10.1 raises:

> Collecting dearpygui==1.10.1 (from -r requirements.txt (line 1))
>   Downloading dearpygui-1.10.1-cp312-cp312-win_amd64.whl.metadata (13 kB)
> Collecting numpy==1.24.1 (from -r requirements.txt (line 2))
>   Downloading numpy-1.24.1.tar.gz (10.9 MB)
>      ━━━━━━━━━━━━━━━━━━━━━━ 10.9/10.9 MB 32.7 MB/s eta 0:00:00
>   Installing build dependencies ... done
>   Getting requirements to build wheel ... error
>   error: subprocess-exited-with-error
>   
>   × Getting requirements to build wheel did not run successfully.
>   │ exit code: 1
>   ╰─> [33 lines of output]
>       Traceback (most recent call last):
> dule
>           return _bootstrap._gcd_import(name[level:], package, level)
>                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
>         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1310, in _find_and_load_unlocked   
>         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed  
>         File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
>         File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
>         File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked   
>         File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
>         File "<frozen importlib._bootstrap_external>", line 994, in exec_module       
>         File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed  
>         File "C:\Users\typedefvoid\AppData\Local\Temp\pip-build-env-9gpiax5c\overlay\Lib\site-packages\setuptools\__init__.py", line 16, in <module>
>           import setuptools.version
>         File "C:\Users\typedefvoid\AppData\Local\Temp\pip-build-env-9gpiax5c\overlay\Lib\site-packages\setuptools\version.py", line 1, in <module>
>           import pkg_resources
>         File "C:\Users\typedefvoid\AppData\Local\Temp\pip-build-env-9gpiax5c\overlay\Lib\site-packages\pkg_resources\__init__.py", line 2172, in <module>
>           register_finder(pkgutil.ImpImporter, find_on_path)
>                           ^^^^^^^^^^^^^^^^^^^
>       AttributeError: module 'pkgutil' has no attribute 'ImpImporter'. Did you mean: 'zipimporter'?
>       [end of output]
> 
>   note: This error originates from a subprocess, and is likely not a problem with pip.
> 
> error: subprocess-exited-with-error
> 
> × Getting requirements to build wheel did not run successfully.
> │ exit code: 1
> ╰─> See above for output.
> 
> note: This error originates from a subprocess, and is likely not a problem with pip.

**Comment by gabrielpie6** [comment]
Seems to be someting pip with package versions conflict:

> pip install pyinstaller==5.7.0
> ERROR: Ignored the following versions that require a different python version: 4.10 Requires-Python <3.11,>=3.6; 4.6 Requires-Python <3.11,>=3.6; 4.7 Requires-Python <3.11,>=3.6; 4.8 Requires-Python <3.11,>=3.6; 4.9 Requires-Python <3.11,>=3.6; 5.0 Requires-Python <3.11,>=3.7; 5.0.1 Requires-Python <3.11,>=3.7; 5.1 Requires-Python <3.11,>=3.7; 5.10.0 Requires-Python <3.12,>=3.7; 5.10.1 Requires-Python <3.12,>=3.7; 5.11.0 Requires-Python <3.12,>=3.7; 5.12.0 Requires-Python <3.12,>=3.7; 5.2 Requires-Python <3.11,>=3.7; 5.3 Requires-Python <3.11,>=3.7; 5.4 Requires-Python <3.11,>=3.7; 5.4.1 Requires-Python <3.11,>=3.7; 5.5 Requires-Python <3.12,>=3.7; 5.6 Requires-Python <3.12,>=3.7; 5.6.1 Requires-Python <3.12,>=3.7; 5.6.2 Requires-Python <3.12,>=3.7; 5.7.0 Requires-Python <3.12,>=3.7; 5.8.0 Requires-Python <3.12,>=3.7; 5.9.0 Requires-Python <3.12,>=3.7
> ERROR: Could not find a version that satisfies the requirement pyinstaller==5.7.0 (from versions: 2.0, 2.1, 3.0, 3.1, 3.1.1, 3.2, 3.2.1, 3.3, 3.3.1, 3.4, 3.5, 3.6, 4.0, 4.1, 4.2, 4.3, 4.4, 4.5, 4.5.1, 5.13.0, 5.13.1, 5.13.2, 6.0.0, 6.1.0, 6.2.0, 6.3.0)
> ERROR: No matching distribution found for pyinstaller==5.7.0

**Comment by gabrielpie6** [comment]
**Solved previous 2 comments migrating Python 3.12 to Python 3.11**
 Changing pip version from 23.3.2 to 23.2.1 doesn't provides any solution.
